version: '3.9'
services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: hello-world-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: thisIsReallyStrongPassword123
      MONGO_INITDB_DATABASE: dev
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    container_name: hello-world-app-backend
    build: ./packages/backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: hello-world-app-frontend
    build: ./packages/frontend
    ports:
      - "3000:3000"