version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: hello-world-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: thisIsReallyStrongPassword123
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_COLLECTION: test
    ports:
      - 27017:27017
    volumes:
      - ./.devcontainer/docker/mongodb/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro

  backend:
    container_name: hello-world-app-backend
    build: ./packages/backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: thisIsReallyStrongPassword123
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_COLLECTION: test
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: hello-world-app-frontend
    build: ./packages/frontend
    ports:
      - "80:80"
