version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-hello-world-app}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        NODE_VERSION: ${NODE_VERSION:-v18.12.1}
        LOCALE: ${LOCALE:-ja_JP.UTF-8}
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        PORT: ${PORT:-8080}
    tty: true
    environment:
      TZ: ${TIME_ZONE:-Asia/Tokyo}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-dbuser}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-dev}
      MONGO_INITDB_COLLECTION: ${MONGO_INITDB_COLLECTION:-test}
      MONGO_HOST: ${MONGO_HOST:-mongodb}
      MONGO_PORT: ${MONGO_PORT:-27017}
    volumes:
      - ../:/home/${USER_NAME:-vscode}/workspace:cached
    ports:
      - ${WORKSPACE_PORT:-9999}:9999

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-hello-world-app}-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-dbuser}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-dev}
      MONGO_INITDB_COLLECTION: ${MONGO_INITDB_COLLECTION:-test}
    ports:
      - ${MONGO_PORT:-27017}:27017
    logging:
      options:
        max-size: 1g
    volumes:
      - ../.docker/mongodb:/data/db
      - ./docker/mongodb/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
