name: Build Docker Hello World App Backend Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "packages/backend/**"

jobs:
  hello-world-app-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Build & push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          export DOCKER_IMAGE_TAG=${GITHUB_SHA::7}
          export DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/hello-world-app-backend:${DOCKER_IMAGE_TAG}"
          docker build . --file ./packages/backend/Dockerfile --tag ${DOCKER_IMAGE}
          docker push ${DOCKER_IMAGE}