name: Build Docker Hello World App Frontend Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "packages/frontend/**"

jobs:
  hello-world-app-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Build & push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          export DOCKER_IMAGE_TAG=${GITHUB_SHA::7}
          export DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/hello-world-app-frontend:${DOCKER_IMAGE_TAG}"
          docker build . --file ./packages/frontend/Dockerfile --build-arg VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }} --tag ${DOCKER_IMAGE_TAG}
          docker push ${DOCKER_IMAGE}